name: gdgt
channels:
  - conda-forge
dependencies:
  - altair
  - arviz
  - cartopy
  - geopandas
  - jupyter
  - matplotlib
  - netcdf4
  - numpy
  - openpyxl
  - pandas
  - pymc
  - scikit-learn
  - vega_datasets
  - xarray
